# Generated by Django 3.1.7 on 2021-06-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20210620_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
