# Generated by Django 3.1.7 on 2021-06-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20210620_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='current_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
