# Generated by Django 3.1.7 on 2021-06-20 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speedracer', '0001_initial'),
        ('Inventory', '0005_auto_20210620_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('current_amount', models.FloatField(blank=True, default=0, null=True)),
                ('product_location', models.CharField(max_length=40)),
                ('created', models.DateTimeField(blank=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speedracer.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedracer.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
