# Generated by Django 3.1.7 on 2021-06-20 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_auto_20210620_1114'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table='Inventory',
        ),
    ]
