# Generated by Django 3.1.7 on 2021-06-20 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speedracer', '0001_initial'),
        ('Inventory', '0008_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='price',
        ),
        migrations.AddField(
            model_name='position',
            name='current_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speedracer.order'),
        ),
        migrations.AddField(
            model_name='position',
            name='product_location',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
