# Generated by Django 3.1.7 on 2021-06-20 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speedracer', '0001_initial'),
        ('Inventory', '0009_auto_20210620_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='product_location',
        ),
        migrations.AlterField(
            model_name='position',
            name='current_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='speedracer.order'),
        ),
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
