# Generated by Django 3.1.7 on 2021-06-20 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_auto_20210620_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='product_location',
        ),
        migrations.RemoveField(
            model_name='position',
            name='product_location',
        ),
    ]
