# Generated by Django 3.1.7 on 2021-06-20 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speedracer', '0001_initial'),
        ('Inventory', '0012_auto_20210620_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='current_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='speedracer.order'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='inventory',
            table=None,
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
