# Generated by Django 3.1.7 on 2021-06-20 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speedracer', '0001_initial'),
        ('Inventory', '0013_auto_20210620_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('current_amount', models.FloatField(blank=True)),
                ('created', models.DateTimeField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedracer.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedracer.product')),
            ],
        ),
    ]
