# Generated by Django 3.1.7 on 2021-06-20 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speedracer', '0001_initial'),
        ('Inventory', '0014_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='current_amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speedracer.order'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
